version: '3'
services:

  mongodb:
    image: mongo:4.4
    container_name: 'mongo_tweets'
    ports:
    - 27018:27017

  tweet_collector:
    build: tweet_collector/
    container_name: 'tweet_collector'
    volumes:
    - ./tweet_collector/:/app
    depends_on:
    - mongodb   
    - postgresdb 

  
  postgresdb:
    image: postgres
    container_name: 'postgres'
    ports:
      - 5555:5432
      # Port OUTSIDE Container:Port INSIDE Container
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=******
      - POSTGRES_DB=tsla_tweets

  etl_job:
    build: etl_job/
    container_name: 'etl'
    volumes:
      - ./etl_job/:/app
    depends_on:
      - postgresdb
      - mongodb
      - tweet_collector